language: node_js
node_js:
  - '10'
sudo: required
dist: trusty
before_install:
  - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
  - npm install
  - npm run installdev
  - npm run bundle-dev
addons:
  artifacts: true
before_deploy:
  - npm -g install asar
  - asar pack dist ui.asar
  - >
    git tag -f "v$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: dev-es6
    tags: true
- provider: releases
  api_key:
    secure: Xa2aIga7tyQWfBYqGcnXyO/xUVreU0BTz9Bc8GljxsZJfWmWRKPFnnAonzbtmUf+YupGXtYHzbA+hvjm2ifbEkc7sNsa67FywDSh9TeY2ZpAAXgI1gkE4m3PX+OJlE7O0YPGSt7oQl0KcfN+SWR9P42yyok/WlKB+OI7fFgQv35zAk1Q4k3dleJp21pmepHtgK9ZJpv1BgpipQF2nPK2Om6QfS13DX7O8HBfHQpSmJEFpderUyxbYd9ikaIo3fOw1WbZecHu9Xc8tSUsc7ZOVQIxUKI0aKiwkLvJxtZapMMabNVPuYbiS0mAtUEXduDx4c4f8SxpzS1cTCkSOLliekg8oOjohNYKDBzC3rLIJq6eYXjFfuNFjEb/eSbv+sCUmbakSidxnph5LDnkdh3DPXnBtN229v7iLFyTwRqEwbhK/r5RP8yNc9r7ZlRFbGTQTWB2VBaJex2LvWqvD2LUzE9YsSVx19RN8Xda71rMC1FanTVcFjKnjh0xmUXlmxxB3hP3196+BlZqEhTqvypAfVEojH13YHhVYb6K8nfc43raWvN5YHxWTz8fW14jdA1qKNgEOfI8KsQmikKtSYbi6/t2jWYGLg180VaZCyvOMQr/P802MTXq2AjmNziHooRIULx1t+LDii38umXxV9EH4Vet5eJVg/7szu7tqTQ1PBY=
  file_glob: true
  file: ui.asar
  skip_cleanup: true
  on:
    branch: dev-es6
    tags: true
